[workspace]
resolver = "2"

members = [
  # Please don't remove the following line, we use it to automatically
  # detect insertion point for newly generated crates.
  # @@INSERTION_POINT@@
  "tests",
]

[profile.release]
overflow-checks = true
strip = true
codegen-units = 1

# TODO: Will be deleted after release
[replace]
"ckb-std:0.15.3" = { git = "https://github.com/nervosnetwork/ckb-std.git", branch = "master" }
"ckb-x64-simulator:0.8.0" = { git = "https://github.com/joii2020/ckb-x64-simulator.git", branch = "main" }
"ckb-testtool:0.12.0" = { git = "https://github.com/joii2020/ckb-testtool.git", branch = "main" }